neighborhood_to_pd: dict = {
    "O'Hare": 16,
    "Schorsch Forest View": 16,
    "O'Hare International Airport": 16,
    "Edison Park": 16,
    "Norwood Park": 16,
    "Jefferson Park": 16,
    "North Park": 17,
    "West Ridge": 24,
    "Rogers Park": 24,
    "Edgewater": 20,
    "Andersonville": 20,
    "Lincoln Square": 20,
    "Ravenswood": 20,
    "Albany Park": 17,
    "Ravenswood Manor": 20,
    "Jefferson Park": 16,
    "Dunning": 16,
    "Portage Park": 16,
    "Irving Park": 17,
    "North Center": 19,
    "Uptown": 19,
    "Lake View": 19,
    "View": 19,
    "Wrigleyville": 19,
    "Boystown": 19,
    "Avondale": 14,
    "Hermosa": 14,
    "Belmont Gardens": 14,
    "Montclare": 25,
    "Belmont Cragin": 25,
    "Cragin": 25,
    "Bucktown": 14,
    "Logan Square": 14,
    "Lincoln Park": 18,
    "Sheffield": 18,
    "DePaul": 18,
    "Galewood": 25,
    "Austin": 15,
    "North Austin": 15,
    "South Austin": 15,
    "Humboldt Park": 11,
    "West Humboldt Park": 11,
    "Wicker Park": 12,
    "Ukrainian Village": 12,
    "East Ukrainian Village": 12,
    "East Village": 12,
    "West Town": 12,
    "River West": 12,
    "Noble Square": 12,
    "River North": 18,
    "Goose Island": 18,
    "Cabrini Green": 18,
    "Near North": 18,
    "Old Town": 18,
    "Old Town Triangle": 18,
    "Gold Coast": 18,
    "Rush & Division": 18,
    "Streeterville": 18,
    "Magnificent Mile": 18,
    "Garfield Park": 11,
    "East Garfield Park": 11,
    "West Garfield Park": 11,
    "United Center": 12,
    "West Loop": 12,
    "Fulton River District": 12,
    "Near West Side": 12,
    "Greektown": 12,
    "Loop": 1,
    "New Eastside": 1,
    "The Loop": 1,
    "West Loop Gate": 1,
    "Millennium Park": 1,
    "Grant Park": 1,
    "Printers Row": 1,
    "University Village - Little Italy": 12,
    "Illinois Medical District": 12,
    "North Lawndale": 10,
    "Little Village": 10,
    "Lower West Side": 12,
    "Pilsen": 12,
    "Near South Side": 1,
    "South Loop": 1,
    "Museum Campus": 1,
    "Heart of Chicago": 12,
    "China Town": 9,
    "Douglas": 2,
    "Groveland Park": 2,
    "South Commons": 2,
    "Lake Meadows": 2,
    "Bronzeville": 2,
    "Douglas Park": 2,
    "Armor Square": 9,
    "Bridgeport": 9,
    "Canaryville": 9,
    "McKinley Park": 9,
    "Brighton Park": 8,
    "Archer Heights": 8,
    "Garfield Ridge": 8,
    "West Elsdon": 8,
    "Gage Park": 8,
    "New City": 9,
    "Back of the Yards": 9,
    "Fuller Park": 9,
    "Grand Boulevard": 2,
    "Oakland": 2,
    "Kenwood": 2,
    "North Kenwood": 2,
    "Hyde Park": 2,
    "Washington Park": 2,
    "Englewood": 7,
    "West Englewood": 7,
    "Jackson Park": 3,
    "Woodlawn": 3,
    "West Woodlawn": 3,
    "Chicago Lawn": 8,
    "Marquette Park": 8,
    "West Lawn": 8,
    "Ashburn": 8,
    "Wrightwood": 8,
    "Auburn Gresham": 6,
    "Gresham": 6,
    "Grand Crossing": 3,
    "Winneconna Parkway": 3,
    "Park Manor": 3,
    "South Shore": 3,
    "South Chicago": 4,
    "South East Ravenswood": 4,
    "Avalon Park": 4,
    "Chatham": 6,
    "West Chatham": 6,
    "East Chatham": 6,
    "Auburn Gresham": 6,
    "Ashburn": 8,
    "Scottsdale": 8,
    "Calumet Heights": 4,
    "Burnside": 4,
    "Beverly": 22,
    "East Beverly": 22,
    "Washington Heights": 22,
    "Brainerd": 22,
    "Roseland": 5,
    "West Chesterfield": 5,
    "Rosemoor": 5,
    "Pullman": 5,
    "South Deering": 4,
    "Lake Calumet": 4,
    "Jeffery Manor": 4,
    "East Side": 4,
    "Mount Greenwood": 22,
    "Morgan Park": 22,
    "West Pullman": 5,
    "Riverdale": 5,
    "Eden Green": 5,
    "Hegewisch": 4,
}

district_to_crime: dict = {
    1: 1992,
    2: 1247,
    3: 1537,
    4: 1648,
    5: 1877,
    6: 2565,
    7: 2414,
    8: 1910,
    9: 1617,
    10: 2238,
    11: 5251,
    12: 1361,
    14: 886,
    15: 1822,
    16: 1323,
    17: 635,
    18: 1481,
    19: 1134,
    20: 434,
    22: 1224,
    24: 867,
    25: 2118,
}
